### ISSUE TITLE
problem installing your program

### ISSUE THREAD

**Issue by jr751** [Voudy/image_morphing#1]
I tried to install your program, and I followed the instructions exactly, but I get an error message. I did the commands:

git clone https://github.com/Voudy/image_morphing.git
cd image_morphing
mkdir build
cd build
cmake ..

Everything works properly until I type in the last command `make`. When I do that, I receive the following error message:

`[ 50%] Building CXX object CMakeFiles/image_morphing.dir/main.cpp.o
/home/jr/image_morphing/main.cpp: In function ‘void draw_point(cv::Mat&, const Point2f&, const Scalar&)’:
/home/jr/image_morphing/main.cpp:17:31: error: ‘CV_FILLED’ was not declared in this scope
     circle(img, fp, 2, color, CV_FILLED, CV_AA, 0);
                               ^~~~~~~~~
/home/jr/image_morphing/main.cpp:17:31: note: suggested alternative: ‘__FILE’
     circle(img, fp, 2, color, CV_FILLED, CV_AA, 0);
                               ^~~~~~~~~
                               __FILE
/home/jr/image_morphing/main.cpp:17:42: error: ‘CV_AA’ was not declared in this scope
     circle(img, fp, 2, color, CV_FILLED, CV_AA, 0);
                                          ^~~~~
/home/jr/image_morphing/main.cpp:17:42: note: suggested alternative: ‘CV_8U’
     circle(img, fp, 2, color, CV_FILLED, CV_AA, 0);
                                          ^~~~~
                                          CV_8U
/home/jr/image_morphing/main.cpp: In function ‘void draw_triangulation(cv::Mat&, cv::Subdiv2D&, const Scalar&)’:
/home/jr/image_morphing/main.cpp:32:56: error: ‘CV_AA’ was not declared in this scope
             line(img, pt[0], pt[1], delaunay_color, 1, CV_AA, 0);
                                                        ^~~~~
/home/jr/image_morphing/main.cpp:32:56: note: suggested alternative: ‘CV_8U’
             line(img, pt[0], pt[1], delaunay_color, 1, CV_AA, 0);
                                                        ^~~~~
                                                        CV_8U
CMakeFiles/image_morphing.dir/build.make:62: recipe for target 'CMakeFiles/image_morphing.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/image_morphing.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/image_morphing.dir/all' failed
make[1]: *** [CMakeFiles/image_morphing.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

Why is this occurring, and how do I think this problem? I am using Linux Mint.

**Comment by SpirinEgor** [comment]
Hi!
Thank you for your attention to my work!

Did you install OpenCV before building this project? Did you specify all paths, so GCC could found it?
In addition, there may be problems with versions, I wrote this code 2 years ago, during this time there may have been changes in the code. Which version are you using?

**Comment by jr751** [comment]
I installed OpenCV properly from source I believe. When I run the command `pkg-config --modversion opencv4` it returns the opencv version number which is 4.4.0. I don't know how to specify all paths so that GCC finds it. How do I do that?

**Comment by SpirinEgor** [comment]
It seems that in OpenCV 4 `CV_FILLED` is removed and you should use `cv::FILLED`. See this [answer](https://answers.opencv.org/question/203960/is-cv_filled-removed-in-400/).
So, can you try changing this on line 17 in `main.cpp`?

**Comment by jr751** [comment]
No, still doesn't work. I made the change to line 17, but I am still getting the same error message shown below when I get to the make step:
`/home/jr/image_morphing/main.cpp: In function ‘void draw_point(cv::Mat&, const Point2f&, const Scalar&)’:
/home/jr/image_morphing/main.cpp:17:43: error: ‘CV_AA’ was not declared in this scope
     circle(img, fp, 2, color, cv::FILLED, CV_AA, 0);
                                           ^~~~~
/home/jr/image_morphing/main.cpp:17:43: note: suggested alternative: ‘CV_8U’
     circle(img, fp, 2, color, cv::FILLED, CV_AA, 0);
                                           ^~~~~
                                           CV_8U
/home/jr/image_morphing/main.cpp: In function ‘void draw_triangulation(cv::Mat&, cv::Subdiv2D&, const Scalar&)’:
/home/jr/image_morphing/main.cpp:32:56: error: ‘CV_AA’ was not declared in this scope
             line(img, pt[0], pt[1], delaunay_color, 1, CV_AA, 0);
                                                        ^~~~~
/home/jr/image_morphing/main.cpp:32:56: note: suggested alternative: ‘CV_8U’
             line(img, pt[0], pt[1], delaunay_color, 1, CV_AA, 0);
                                                        ^~~~~
                                                        CV_8U
CMakeFiles/image_morphing.dir/build.make:62: recipe for target 'CMakeFiles/image_morphing.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/image_morphing.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/image_morphing.dir/all' failed
make[1]: *** [CMakeFiles/image_morphing.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

I also tried chaning CV_AA to cv::AA on line 17 too, but that doesn't fix things either.

**Comment by jr751** [comment]
Ahh...nevermind. I just figured it out. I had to change CV_AA to LINE_AA too. I would add a pull request, but I don't know how to do that.

Egor, thanks for your help and writing this code. It works perfectly now!

**Comment by SpirinEgor** [comment]
Glad to hear that everything worked!

Feel free to open a pull request, I will review it and add it to the master branch. For this, you need to fork the repository, make changes in it (fix the problem and push to GitHub) and after that, you can create a pull request throw site (just click "New pull request"). The full instruction with samples you can find here: https://opensource.com/article/19/7/create-pull-request-github
